#comments: Execute the docker-compose file with up command

version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.9.1
    container_name: selenium-hub
    restart: always
    ports:
      - "4445:4444"
      - "4442:4442"
      - "4443:4443"
  chrome:
    image: selenium/node-chrome:4.9.1
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=1
    depends_on:
      - selenium-hub
    restart: on-failure
  edge:
    image: selenium/node-edge:4.9.1
    shm_size: "2gb"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=1
    depends_on:
      - selenium-hub
    restart: on-failure